export const allowedTags = [
  "a",
  "abbr",
  "b",
  "blockquote",
  "br",
  "center",
  "cite",
  "code",
  "dd",
  "del",
  "details",
  "dfn",
  "div",
  "dl",
  "dt",
  "em",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hr",
  "i",
  "iframe",
  "img",
  "ins",
  "kbd",
  "li",
  "mark",
  "ol",
  "p",
  "pre",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "small",
  "span",
  "strike",
  "strong",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "tfoot",
  "th",
  "thead",
  "time",
  "tr",
  "tt",
  "u",
  "ul",
  "var",
  "video",
] as const;

export type AllowedTag = (typeof allowedTags)[number];

export const globalAllowedAttributes = new Set(["title", "style"]);

export const tagAttributes: Record<AllowedTag, string[]> = {
  a: ["href", "name"],
  abbr: ["title"],
  b: [],
  blockquote: ["cite"],
  br: [],
  center: [],
  cite: [],
  code: [],
  dd: [],
  del: [],
  details: ["open"],
  dfn: ["title"],
  div: [],
  dl: [],
  dt: [],
  em: [],
  h1: [],
  h2: [],
  h3: [],
  h4: [],
  h5: [],
  h6: [],
  hr: [],
  i: [],
  iframe: ["allowfullscreen", "frameborder", "height", "src", "width"],
  img: ["src", "alt", "height", "width"],
  ins: [],
  kbd: [],
  li: [],
  mark: [],
  ol: [],
  p: [],
  pre: [],
  q: ["cite"],
  rp: [],
  rt: [],
  ruby: [],
  s: [],
  samp: [],
  small: [],
  span: [],
  strike: [],
  strong: [],
  sub: [],
  summary: [],
  sup: [],
  table: [],
  tbody: [],
  td: [],
  tfoot: [],
  th: [],
  thead: [],
  time: ["datetime", "pubdate"],
  tr: [],
  tt: [],
  u: [],
  ul: [],
  var: [],
  video: ["src", "poster", "height", "width"],
};

export const tagCategories: Record<AllowedTag, string> = {
  a: "Links",
  abbr: "Inline Text",
  b: "Inline Text",
  blockquote: "Text Blocks",
  br: "Text Blocks",
  center: "Layout",
  cite: "Inline Text",
  code: "Code",
  dd: "Lists",
  del: "Inline Text",
  details: "Interactive",
  dfn: "Inline Text",
  div: "Layout",
  dl: "Lists",
  dt: "Lists",
  em: "Inline Text",
  h1: "Headings",
  h2: "Headings",
  h3: "Headings",
  h4: "Headings",
  h5: "Headings",
  h6: "Headings",
  hr: "Layout",
  i: "Inline Text",
  iframe: "Media",
  img: "Media",
  ins: "Inline Text",
  kbd: "Code",
  li: "Lists",
  mark: "Inline Text",
  ol: "Lists",
  p: "Text Blocks",
  pre: "Code",
  q: "Inline Text",
  rp: "Ruby",
  rt: "Ruby",
  ruby: "Ruby",
  s: "Inline Text",
  samp: "Code",
  small: "Inline Text",
  span: "Inline Text",
  strike: "Inline Text",
  strong: "Inline Text",
  sub: "Inline Text",
  summary: "Interactive",
  sup: "Inline Text",
  table: "Tables",
  tbody: "Tables",
  td: "Tables",
  tfoot: "Tables",
  th: "Tables",
  thead: "Tables",
  time: "Inline Text",
  tr: "Tables",
  tt: "Code",
  u: "Inline Text",
  ul: "Lists",
  var: "Code",
  video: "Media",
};
